"""Declarative base and the column mixins every entity shares (taskbook §9).

§9 requires that all main entities carry ``id``, ``created_at`` and
``updated_at``; workspace-scoped entities add ``workspace_id``; soft-deletable
ones add ``deleted_at``. Expressing those as mixins rather than repeating them
per model is what keeps the rule enforceable — a table that forgets
``workspace_id`` is a tenant isolation bug, and it should be hard to write.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import ClassVar

from sqlalchemy import DateTime, ForeignKey, Index, MetaData, func, text
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column

from backend_core.db.metadata import metadata as shared_metadata


class Base(DeclarativeBase):
    """Declarative base bound to the shared metadata.

    Binding to :data:`backend_core.db.metadata.metadata` rather than letting
    SQLAlchemy create its own is what lets Alembic autogeneration see every
    table through one object, with the constraint naming convention applied.
    """

    # ClassVar because DeclarativeBase declares it as one; a plain annotation
    # would redeclare it as an instance attribute.
    metadata: ClassVar[MetaData] = shared_metadata


class UUIDPrimaryKeyMixin:
    """A UUID primary key generated by the database (§9).

    UUIDs rather than serial integers because ids appear in URLs and object
    keys: a sequential id leaks how many products a competitor's workspace
    holds and makes enumeration trivial.

    ``gen_random_uuid()`` is Postgres 13+ built-in — no ``pgcrypto`` needed.
    Defaulting server-side means a row inserted by a migration or by hand still
    gets a valid id.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        postgresql.UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        default=uuid.uuid4,
    )


class TimestampMixin:
    """``created_at`` / ``updated_at``, always timezone-aware UTC (§9, §129).

    Both defaults are server-side: ``now()`` from the database gives one clock
    for every writer, where application clocks drift between machines.
    ``onupdate`` covers ORM writes; a migration touching rows directly sets it
    explicitly.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class WorkspaceScopedMixin:
    """``workspace_id`` plus the index every scoped query needs (§9).

    Declared as a mixin so tenant scoping is one line to add and conspicuous
    when missing. ``ON DELETE CASCADE`` matches the deletion policy: removing a
    workspace removes its data, while individual records use soft deletion
    (§112) so project history is never broken by a stray delete.
    """

    @declared_attr
    @classmethod
    def workspace_id(cls) -> Mapped[uuid.UUID]:
        return mapped_column(
            postgresql.UUID(as_uuid=True),
            ForeignKey("workspaces.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )


class SoftDeleteMixin:
    """``deleted_at`` for entities that must survive deletion (§112).

    Deleting a product hides it but must not break the projects that reference
    its assets. Storage objects are marked orphaned and collected later by a
    background GC rather than removed inline.
    """

    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
    )

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None


class BaseEntity(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """Convenience base for a non-workspace-scoped entity (users, workspaces)."""

    __abstract__ = True


class WorkspaceEntity(Base, UUIDPrimaryKeyMixin, WorkspaceScopedMixin, TimestampMixin):
    """Convenience base for a workspace-scoped entity — most of the schema."""

    __abstract__ = True


def workspace_scoped_index(table_name: str, *columns: str) -> Index:
    """Build a composite index led by ``workspace_id``.

    Column order matters: every scoped query filters on ``workspace_id`` first,
    so leading with it lets one index serve both the tenant filter and the
    secondary predicate (§9 "high-frequency filter fields get an index").
    """
    name = f"ix_{table_name}_workspace_id_{'_'.join(columns)}"
    return Index(name, "workspace_id", *columns)
