"""Domain layer — entities, enums and state machines.

The rules that stay true regardless of how data is stored or exposed: the
Product (§104), Project (§105) and Job (§106) state machines, the role model
(§40), and the verification states that make the Truth Layer work (§13).

State transitions are validated here, never by assigning a string to a status
column — §105 is explicit that arbitrary status writes are forbidden.

Importing this package registers every model with the shared metadata, which
is what lets Alembic autogeneration see the full schema.
"""

from backend_core.domain.enums import (
    FACT_BACKED_CLAIM_TYPES,
    PLATFORM_DEFAULT_ASPECT,
    ROLE_PERMISSIONS,
    SCRIPT_SECTIONS,
    AnalysisStatus,
    AspectRatio,
    AssetSourceType,
    AssetType,
    ClaimRiskLevel,
    ClaimStatus,
    ClaimType,
    FactSourceType,
    FactType,
    JobStatus,
    JobType,
    LicenseType,
    Permission,
    PlanCode,
    ProductAssetRole,
    ProductStatus,
    ProjectPurpose,
    ProjectStatus,
    QCCheckType,
    QCStatus,
    QualityMode,
    ReferenceRole,
    RenderStatus,
    ScriptStatus,
    ShotStatus,
    ShotType,
    StoryboardStatus,
    TargetPlatform,
    TrackType,
    TransitionType,
    UploadStatus,
    UserStatus,
    VerificationStatus,
    VideoStyle,
    VoiceGender,
    WorkspaceRole,
    WorkspaceStatus,
    allowed_product_transitions,
    allowed_project_transitions,
    can_transition_job,
    can_transition_product,
    can_transition_project,
    default_risk_level,
    permissions_for,
    requires_fact_backing,
    role_has_permission,
    role_rank,
)
from backend_core.domain.models import (
    AudioTrack,
    CreativePlan,
    GenerationJob,
    MediaAsset,
    Product,
    ProductAnalysis,
    ProductAsset,
    ProductClaim,
    ProductFact,
    Project,
    ProviderJob,
    QualityCheck,
    Render,
    Script,
    Shot,
    ShotReference,
    Storyboard,
    SubtitleTrack,
    User,
    VoiceoverTrack,
    Workspace,
    WorkspaceMember,
)

__all__ = [
    "FACT_BACKED_CLAIM_TYPES",
    "PLATFORM_DEFAULT_ASPECT",
    "ROLE_PERMISSIONS",
    "SCRIPT_SECTIONS",
    "AnalysisStatus",
    "AspectRatio",
    "AssetSourceType",
    "AssetType",
    "AudioTrack",
    "ClaimRiskLevel",
    "ClaimStatus",
    "ClaimType",
    "CreativePlan",
    "FactSourceType",
    "FactType",
    "GenerationJob",
    "JobStatus",
    "JobType",
    "LicenseType",
    "MediaAsset",
    "Permission",
    "PlanCode",
    "Product",
    "ProductAnalysis",
    "ProductAsset",
    "ProductAssetRole",
    "ProductClaim",
    "ProductFact",
    "ProductStatus",
    "Project",
    "ProjectPurpose",
    "ProjectStatus",
    "ProviderJob",
    "QCCheckType",
    "QCStatus",
    "QualityCheck",
    "QualityMode",
    "ReferenceRole",
    "Render",
    "RenderStatus",
    "Script",
    "ScriptStatus",
    "Shot",
    "ShotReference",
    "ShotStatus",
    "ShotType",
    "Storyboard",
    "StoryboardStatus",
    "SubtitleTrack",
    "TargetPlatform",
    "TrackType",
    "TransitionType",
    "UploadStatus",
    "User",
    "UserStatus",
    "VerificationStatus",
    "VideoStyle",
    "VoiceGender",
    "VoiceoverTrack",
    "Workspace",
    "WorkspaceMember",
    "WorkspaceRole",
    "WorkspaceStatus",
    "allowed_product_transitions",
    "allowed_project_transitions",
    "can_transition_job",
    "can_transition_product",
    "can_transition_project",
    "default_risk_level",
    "permissions_for",
    "requires_fact_backing",
    "role_has_permission",
    "role_rank",
]
