"""credit accounts and transactions

Revision ID: ffc7cc2507a6
Revises: 814e072a2d98
Create Date: 2026-08-13 01:38:56.186671+00:00

Every migration must be reversible or document why it is not (taskbook §73).
Fill in ``downgrade()`` — an empty one is only acceptable with a comment
explaining the irreversible operation and the recovery plan.

CHECK BEFORE COMMITTING:

* If this migration adds a column with ``sa.Enum``, autogenerate created a
  Postgres ENUM type but ``drop_table`` will NOT remove it. Add an explicit
  ``op.execute(sa.text("DROP TYPE IF EXISTS <name>"))`` to ``downgrade()``,
  or the next ``upgrade`` fails with "type already exists".
* Run ``upgrade -> downgrade -> upgrade`` against a real database. A downgrade
  that has never been executed is not known to work.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ffc7cc2507a6"
down_revision: str | None = "814e072a2d98"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_accounts",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("balance", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("reserved", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("lifetime_granted", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("lifetime_spent", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("monthly_limit", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "balance >= 0", name=op.f("ck_credit_accounts_balance_non_negative")
        ),
        sa.CheckConstraint(
            "reserved <= balance",
            name=op.f("ck_credit_accounts_reserved_within_balance"),
        ),
        sa.CheckConstraint(
            "reserved >= 0",
            name=op.f("ck_credit_accounts_reserved_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_credit_accounts_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_accounts")),
        sa.UniqueConstraint("workspace_id", name=op.f("uq_credit_accounts_workspace_id")),
    )
    op.create_table(
        "credit_transactions",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum(
                "GRANT",
                "RESERVE",
                "CAPTURE",
                "RELEASE",
                "REFUND",
                "ADJUSTMENT",
                "EXPIRY",
                name="credit_transaction_type",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("balance_after", sa.Float(), nullable=False),
        sa.Column("reserved_after", sa.Float(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=500), server_default="", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount >= 0",
            name=op.f("ck_credit_transactions_amount_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["credit_accounts.id"],
            name=op.f("fk_credit_transactions_account_id_credit_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_credit_transactions_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["generation_jobs.id"],
            name=op.f("fk_credit_transactions_job_id_generation_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_credit_transactions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_transactions")),
        sa.UniqueConstraint(
            "workspace_id", "idempotency_key", name="uq_credit_transactions_idempotency"
        ),
    )
    op.create_index(
        "ix_credit_transactions_account_created",
        "credit_transactions",
        ["account_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_credit_transactions_job_id", "credit_transactions", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_credit_transactions_workspace_id"),
        "credit_transactions",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_credit_transactions_workspace_id_created_at",
        "credit_transactions",
        ["workspace_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_credit_transactions_workspace_id_created_at", table_name="credit_transactions"
    )
    op.drop_index(op.f("ix_credit_transactions_workspace_id"), table_name="credit_transactions")
    op.drop_index("ix_credit_transactions_job_id", table_name="credit_transactions")
    op.drop_index("ix_credit_transactions_account_created", table_name="credit_transactions")
    op.drop_table("credit_transactions")
    op.drop_table("credit_accounts")

    # `drop_table` leaves the ENUM type behind; the next `upgrade` would fail
    # with "type already exists".
    op.execute(sa.text("DROP TYPE IF EXISTS credit_transaction_type"))
