"""media assets

Revision ID: 9553d8543e89
Revises: c9b914c381bc
Create Date: 2026-08-12 00:57:47.871162+00:00

Adds ``media_assets`` (§10.17) — the single table that references objects in
storage. Binary content itself never enters Postgres (§9); what lands here is
bucket + key plus the metadata needed to serve, validate and garbage-collect
the file without fetching it.

Reversible: ``downgrade`` drops the table, its indexes and the three ENUM types
this migration creates. Verified by running upgrade → downgrade → upgrade.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9553d8543e89"
down_revision: str | None = "c9b914c381bc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_assets",
        sa.Column(
            "asset_type",
            sa.Enum(
                "IMAGE", "VIDEO", "AUDIO", "SUBTITLE", "DOCUMENT", "THUMBNAIL", name="asset_type"
            ),
            nullable=False,
        ),
        sa.Column(
            "source_type",
            sa.Enum("USER_UPLOAD", "AI_GENERATED", "RENDERED", "DERIVED", name="asset_source_type"),
            nullable=False,
        ),
        sa.Column(
            "upload_status",
            sa.Enum("PENDING", "READY", "FAILED", name="upload_status"),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("bucket", sa.String(length=128), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("fps", sa.Float(), nullable=True),
        sa.Column("codec", sa.String(length=64), nullable=True),
        sa.Column("checksum", sa.String(length=128), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "starts_with(object_key, 'workspaces/' || workspace_id::text || '/')",
            name=op.f("ck_media_assets_object_key_is_workspace_scoped"),
        ),
        sa.CheckConstraint(
            "upload_status <> 'READY' OR size_bytes IS NOT NULL",
            name=op.f("ck_media_assets_ready_assets_have_size"),
        ),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0",
            name=op.f("ck_media_assets_duration_non_negative"),
        ),
        sa.CheckConstraint("fps IS NULL OR fps > 0", name=op.f("ck_media_assets_fps_positive")),
        sa.CheckConstraint(
            "height IS NULL OR height > 0", name=op.f("ck_media_assets_height_positive")
        ),
        sa.CheckConstraint(
            "size_bytes IS NULL OR size_bytes >= 0",
            name=op.f("ck_media_assets_size_bytes_non_negative"),
        ),
        sa.CheckConstraint(
            "width IS NULL OR width > 0", name=op.f("ck_media_assets_width_positive")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_media_assets_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
        sa.UniqueConstraint("bucket", "object_key", name="uq_media_asset_object"),
    )
    op.create_index(
        op.f("ix_media_assets_deleted_at"), "media_assets", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_media_assets_pending_created_at",
        "media_assets",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("upload_status = 'PENDING'"),
    )
    op.create_index(
        op.f("ix_media_assets_workspace_id"), "media_assets", ["workspace_id"], unique=False
    )
    op.create_index(
        "ix_media_assets_workspace_id_asset_type",
        "media_assets",
        ["workspace_id", "asset_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_media_assets_workspace_id_asset_type", table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_workspace_id"), table_name="media_assets")
    op.drop_index(
        "ix_media_assets_pending_created_at",
        table_name="media_assets",
        postgresql_where=sa.text("upload_status = 'PENDING'"),
    )
    op.drop_index(op.f("ix_media_assets_deleted_at"), table_name="media_assets")
    op.drop_table("media_assets")
    # ### end Alembic commands ###

    # Hand-added: `drop_table` leaves the ENUM types behind, so the next
    # `upgrade` would fail with "type ... already exists". Autogenerate does
    # not emit these — see the checklist in script.py.mako.
    for enum_name in ("upload_status", "asset_source_type", "asset_type"):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
