"""products facts and claims

Revision ID: 0b6ac8e2e56b
Revises: 9553d8543e89
Create Date: 2026-08-12 01:35:53.484174+00:00

Adds the product tables and the Truth Layer (§10.5-§10.8): `products`,
`product_assets`, `product_facts` and `product_claims`.

Two CHECK constraints here are load-bearing rather than defensive. A fact or
claim marked `VERIFIED` must carry a `verified_at`, so a single missed
assignment on one code path cannot produce something that claims to be
human-confirmed with no record of when — §13's guarantee is only as strong as
its weakest write.

Reversible: `downgrade` drops the tables, their indexes and the seven ENUM
types created here. Verified by running upgrade -> downgrade -> upgrade.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0b6ac8e2e56b"
down_revision: str | None = "9553d8543e89"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=120), nullable=False),
        sa.Column("brand_name", sa.String(length=120), nullable=True),
        sa.Column("sku", sa.String(length=120), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ASSETS_READY",
                "ANALYZING",
                "REVIEW_REQUIRED",
                "READY",
                "ARCHIVED",
                name="product_status",
            ),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column("ai_summary", sa.Text(), nullable=True),
        sa.Column(
            "visual_dna",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "length(trim(category)) > 0", name=op.f("ck_products_category_not_blank")
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_products_name_not_blank")),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_products_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(op.f("ix_products_deleted_at"), "products", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_products_workspace_id"), "products", ["workspace_id"], unique=False)
    op.create_index(
        "ix_products_workspace_id_status", "products", ["workspace_id", "status"], unique=False
    )
    op.create_index(
        "uq_products_workspace_id_sku",
        "products",
        ["workspace_id", "sku"],
        unique=True,
        postgresql_where=sa.text("sku IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_table(
        "product_assets",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("media_asset_id", sa.UUID(), nullable=False),
        sa.Column(
            "asset_role",
            sa.Enum(
                "FRONT",
                "SIDE",
                "BACK",
                "ANGLE_45",
                "PACKAGING",
                "LOGO",
                "DETAIL",
                "MATERIAL",
                "SCENE",
                "STRUCTURE",
                "OTHER",
                name="product_asset_role",
            ),
            server_default="OTHER",
            nullable=False,
        ),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["media_asset_id"],
            ["media_assets.id"],
            name=op.f("fk_product_assets_media_asset_id_media_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_assets_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_product_assets_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_assets")),
        sa.UniqueConstraint("product_id", "media_asset_id", name="uq_product_asset"),
    )
    op.create_index(
        "ix_product_assets_product_id_sort_order",
        "product_assets",
        ["product_id", "sort_order"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_assets_workspace_id"), "product_assets", ["workspace_id"], unique=False
    )
    op.create_index(
        "uq_product_assets_primary",
        "product_assets",
        ["product_id"],
        unique=True,
        postgresql_where=sa.text("is_primary"),
    )
    op.create_table(
        "product_claims",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("claim_text", sa.Text(), nullable=False),
        sa.Column(
            "claim_type",
            sa.Enum(
                "FUNCTIONAL",
                "PERFORMANCE",
                "COMPARATIVE",
                "CERTIFICATION",
                "SAFETY",
                "EMOTIONAL",
                name="claim_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "source_fact_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("SUGGESTED", "VERIFIED", "REJECTED", name="claim_status"),
            server_default="SUGGESTED",
            nullable=False,
        ),
        sa.Column(
            "risk_level",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="claim_risk_level"),
            server_default="MEDIUM",
            nullable=False,
        ),
        sa.Column("verified_by_user_id", sa.UUID(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(source_fact_ids) = 'array'",
            name=op.f("ck_product_claims_source_fact_ids_is_array"),
        ),
        sa.CheckConstraint(
            "status <> 'VERIFIED' OR verified_at IS NOT NULL",
            name=op.f("ck_product_claims_verified_claims_have_a_timestamp"),
        ),
        sa.CheckConstraint(
            "length(trim(claim_text)) > 0", name=op.f("ck_product_claims_claim_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_claims_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_user_id"],
            ["users.id"],
            name=op.f("fk_product_claims_verified_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_product_claims_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_claims")),
    )
    op.create_index(
        "ix_product_claims_product_id_status",
        "product_claims",
        ["product_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_claims_workspace_id"), "product_claims", ["workspace_id"], unique=False
    )
    op.create_index(
        "ix_product_claims_workspace_id_product_id",
        "product_claims",
        ["workspace_id", "product_id"],
        unique=False,
    )
    op.create_table(
        "product_facts",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column(
            "fact_type",
            sa.Enum(
                "SPEC",
                "MATERIAL",
                "FEATURE",
                "PERFORMANCE",
                "CERTIFICATION",
                "INGREDIENT",
                "COMPATIBILITY",
                "WARRANTY",
                "PRICING",
                "APPEARANCE",
                "OTHER",
                name="fact_type",
            ),
            nullable=False,
        ),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value_text", sa.Text(), nullable=False),
        sa.Column("value_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum(
                "USER_INPUT", "AI_VISION", "AI_TEXT", "DOCUMENT", "IMPORT", name="fact_source_type"
            ),
            nullable=False,
        ),
        sa.Column("source_asset_id", sa.UUID(), nullable=True),
        sa.Column(
            "verification_status",
            sa.Enum(
                "AI_INFERRED", "USER_PROVIDED", "VERIFIED", "REJECTED", name="verification_status"
            ),
            server_default="AI_INFERRED",
            nullable=False,
        ),
        sa.Column("verified_by_user_id", sa.UUID(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "verification_status <> 'VERIFIED' OR verified_at IS NOT NULL",
            name=op.f("ck_product_facts_verified_facts_have_a_timestamp"),
        ),
        sa.CheckConstraint("length(trim(key)) > 0", name=op.f("ck_product_facts_key_not_blank")),
        sa.CheckConstraint(
            "length(trim(value_text)) > 0", name=op.f("ck_product_facts_value_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_facts_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_asset_id"],
            ["media_assets.id"],
            name=op.f("fk_product_facts_source_asset_id_media_assets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_user_id"],
            ["users.id"],
            name=op.f("fk_product_facts_verified_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_product_facts_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_facts")),
    )
    op.create_index(
        "ix_product_facts_product_id_status",
        "product_facts",
        ["product_id", "verification_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_facts_workspace_id"), "product_facts", ["workspace_id"], unique=False
    )
    op.create_index(
        "ix_product_facts_workspace_id_product_id",
        "product_facts",
        ["workspace_id", "product_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_product_facts_workspace_id_product_id", table_name="product_facts")
    op.drop_index(op.f("ix_product_facts_workspace_id"), table_name="product_facts")
    op.drop_index("ix_product_facts_product_id_status", table_name="product_facts")
    op.drop_table("product_facts")
    op.drop_index("ix_product_claims_workspace_id_product_id", table_name="product_claims")
    op.drop_index(op.f("ix_product_claims_workspace_id"), table_name="product_claims")
    op.drop_index("ix_product_claims_product_id_status", table_name="product_claims")
    op.drop_table("product_claims")
    op.drop_index(
        "uq_product_assets_primary",
        table_name="product_assets",
        postgresql_where=sa.text("is_primary"),
    )
    op.drop_index(op.f("ix_product_assets_workspace_id"), table_name="product_assets")
    op.drop_index("ix_product_assets_product_id_sort_order", table_name="product_assets")
    op.drop_table("product_assets")
    op.drop_index(
        "uq_products_workspace_id_sku",
        table_name="products",
        postgresql_where=sa.text("sku IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_index("ix_products_workspace_id_status", table_name="products")
    op.drop_index(op.f("ix_products_workspace_id"), table_name="products")
    op.drop_index(op.f("ix_products_deleted_at"), table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###

    # Hand-added: `drop_table` leaves the ENUM types behind, so the next
    # `upgrade` would fail with "type ... already exists". Autogenerate does
    # not emit these — see the checklist in script.py.mako.
    for enum_name in (
        "claim_risk_level",
        "claim_status",
        "claim_type",
        "verification_status",
        "fact_source_type",
        "fact_type",
        "product_asset_role",
        "product_status",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
