"""batches and batch items

Revision ID: dc3907046a67
Revises: 973978d06ea4
Create Date: 2026-08-13 06:13:27.381012+00:00

Every migration must be reversible or document why it is not (taskbook §73).
Fill in ``downgrade()`` — an empty one is only acceptable with a comment
explaining the irreversible operation and the recovery plan.

CHECK BEFORE COMMITTING:

* If this migration adds a column with ``sa.Enum``, autogenerate created a
  Postgres ENUM type but ``drop_table`` will NOT remove it. Add an explicit
  ``op.execute(sa.text("DROP TYPE IF EXISTS <name>"))`` to ``downgrade()``,
  or the next ``upgrade`` fails with "type already exists".
* Run ``upgrade -> downgrade -> upgrade`` against a real database. A downgrade
  that has never been executed is not known to work.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "dc3907046a67"
down_revision: str | None = "973978d06ea4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batches",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "VALIDATING",
                "READY",
                "RUNNING",
                "PAUSED",
                "COMPLETED",
                "PARTIAL",
                "FAILED",
                "CANCELED",
                name="batch_status",
            ),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column("template_id", sa.UUID(), nullable=True),
        sa.Column("brand_kit_id", sa.UUID(), nullable=True),
        sa.Column("source_filename", sa.String(length=255), nullable=True),
        sa.Column("source_format", sa.String(length=16), server_default="csv", nullable=False),
        sa.Column("total_items", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("completed_items", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("failed_items", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_concurrency", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "max_concurrency >= 1 AND max_concurrency <= 20",
            name=op.f("ck_batches_max_concurrency_range"),
        ),
        sa.ForeignKeyConstraint(
            ["brand_kit_id"],
            ["brand_kits.id"],
            name=op.f("fk_batches_brand_kit_id_brand_kits"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_batches_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["templates.id"],
            name=op.f("fk_batches_template_id_templates"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_batches_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_batches")),
    )
    op.create_index(op.f("ix_batches_workspace_id"), "batches", ["workspace_id"], unique=False)
    op.create_index(
        "ix_batches_workspace_id_status", "batches", ["workspace_id", "status"], unique=False
    )
    op.create_table(
        "batch_items",
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "INVALID",
                "QUEUED",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "SKIPPED",
                name="batch_item_status",
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column(
            "source_row",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "validation_errors",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batches.id"],
            name=op.f("fk_batch_items_batch_id_batches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_batch_items_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_batch_items_project_id_projects"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_batch_items_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_batch_items")),
        sa.UniqueConstraint("batch_id", "row_number", name="uq_batch_items_row"),
    )
    op.create_index(
        "ix_batch_items_batch_status", "batch_items", ["batch_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_batch_items_workspace_id"), "batch_items", ["workspace_id"], unique=False
    )
    op.create_index(
        "ix_batch_items_workspace_id_status",
        "batch_items",
        ["workspace_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_batch_items_workspace_id_status", table_name="batch_items")
    op.drop_index(op.f("ix_batch_items_workspace_id"), table_name="batch_items")
    op.drop_index("ix_batch_items_batch_status", table_name="batch_items")
    op.drop_table("batch_items")
    op.drop_index("ix_batches_workspace_id_status", table_name="batches")
    op.drop_index(op.f("ix_batches_workspace_id"), table_name="batches")
    op.drop_table("batches")

    # `drop_table` leaves the ENUM types behind; the next `upgrade` would fail
    # with "type already exists".
    op.execute(sa.text("DROP TYPE IF EXISTS batch_item_status"))
    op.execute(sa.text("DROP TYPE IF EXISTS batch_status"))
    # ### end Alembic commands ###
