"""provider configs and platform admin flag

Revision ID: 973978d06ea4
Revises: ffc7cc2507a6
Create Date: 2026-08-13 05:59:10.764005+00:00

Every migration must be reversible or document why it is not (taskbook §73).
Fill in ``downgrade()`` — an empty one is only acceptable with a comment
explaining the irreversible operation and the recovery plan.

CHECK BEFORE COMMITTING:

* If this migration adds a column with ``sa.Enum``, autogenerate created a
  Postgres ENUM type but ``drop_table`` will NOT remove it. Add an explicit
  ``op.execute(sa.text("DROP TYPE IF EXISTS <name>"))`` to ``downgrade()``,
  or the next ``upgrade`` fails with "type already exists".
* Run ``upgrade -> downgrade -> upgrade`` against a real database. A downgrade
  that has never been executed is not known to work.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "973978d06ea4"
down_revision: str | None = "ffc7cc2507a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_configs",
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=120), server_default="", nullable=False),
        sa.Column("kind", sa.String(length=32), server_default="video", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("priority", sa.Integer(), server_default=sa.text("100"), nullable=False),
        sa.Column("cost_per_second", sa.Float(), nullable=True),
        sa.Column("max_concurrency", sa.Integer(), nullable=True),
        sa.Column("circuit_open_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("circuit_trip_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_configs")),
        sa.UniqueConstraint("provider", "kind", name="uq_provider_configs_provider_kind"),
    )
    op.create_index(
        "ix_provider_configs_kind_enabled", "provider_configs", ["kind", "enabled"], unique=False
    )
    op.add_column(
        "users",
        sa.Column(
            "is_platform_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_platform_admin")
    op.drop_index("ix_provider_configs_kind_enabled", table_name="provider_configs")
    op.drop_table("provider_configs")
    # ### end Alembic commands ###
