"""FFmpeg argument construction (§34, §35, PHASE 13).

§35 is a list of prohibitions and this module is written against it:

    禁止: os.system(f"ffmpeg {user_input}")
    必须: subprocess 参数数组; 不使用 shell=True; 参数白名单;
          文件路径由系统生成; 临时目录隔离; 超时; 清理临时文件

So: every argument is a list element, never a string to be word-split. Every
path in the command is one *we* generated inside a temporary directory — no
value that came from a user or a provider is ever a path or a flag. Text that
does reach ffmpeg (a subtitle style, a font name) is either from a closed set
or escaped for the filter grammar.

The reason this matters more here than elsewhere: ffmpeg's filter syntax has
its own metacharacters, so a filename containing `:` or `'` breaks a filter
chain that a shell-quoting review would have called safe. Generating the paths
ourselves sidesteps the entire class.

**The plan is a value, not an execution.** `build_render_plan` returns the
argument list; running it is the worker's job. That split is what makes the
command inspectable in a test and in a log without a render happening.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Final

from backend_core.domain.enums import (
    RENDER_AUDIO_CODEC,
    RENDER_PIXEL_FORMAT,
    RENDER_VIDEO_CODEC,
    TrackType,
)
from backend_core.render.timeline import Timeline

#: §34's output baseline, as encoder flags. `faststart` moves the moov atom to
#: the front so a browser can begin playing before the whole file arrives —
#: without it a 40 MB preview appears broken for several seconds.
_BASE_OUTPUT_ARGS: Final[tuple[str, ...]] = (
    "-c:v",
    RENDER_VIDEO_CODEC,
    "-profile:v",
    "high",
    "-pix_fmt",
    RENDER_PIXEL_FORMAT,
    "-c:a",
    RENDER_AUDIO_CODEC,
    "-b:a",
    "192k",
    "-movflags",
    "+faststart",
)

#: Quality/size trade-off. 20 is visually near-lossless for product footage at
#: these resolutions; lower numbers buy detail nobody will see on a phone at
#: several megabytes a second.
_CRF: Final[str] = "20"

#: §31's styling, applied at burn-in. An outline is not decoration — white text
#: over a white product is invisible without one, and product videos are full
#: of white products.
_SUBTITLE_STYLE: Final[str] = (
    "FontName=Noto Sans CJK SC,FontSize=16,PrimaryColour=&H00FFFFFF,"
    "OutlineColour=&H80000000,BorderStyle=1,Outline=2,Shadow=1,"
    "Alignment=2,MarginV=80"
)


@dataclass(frozen=True, slots=True)
class RenderPlan:
    """A complete, inspectable ffmpeg invocation (§34).

    `argv` is ready for `subprocess.run(..., shell=False)`. Nothing in it needs
    quoting, because nothing in it came from outside.
    """

    argv: list[str]
    output_path: Path
    #: Files the caller must write before running, keyed by path. Kept separate
    #: from `argv` so the worker cannot forget one and discover it as an
    #: ffmpeg error about a missing input.
    sidecar_files: dict[Path, str] = field(default_factory=dict)
    expected_duration_ms: int = 0


def build_render_plan(
    timeline: Timeline,
    *,
    workspace: Path,
    local_paths: dict[str, Path],
    ffmpeg_path: str = "ffmpeg",
    burn_subtitles: bool = True,
    crf: str = _CRF,
) -> RenderPlan:
    """Turn a timeline into an ffmpeg command (§34).

    `local_paths` maps each timeline item's `object_key` to a file the worker
    has already downloaded into `workspace`. Passing them in rather than
    deriving them here keeps this function pure and keeps §35's "paths are
    generated by the system" true by construction — this code never invents a
    path from a key.

    Raises `ValueError` for a timeline that cannot be rendered, which is the
    right moment: after downloads but before an encode that would fail slowly.
    """
    video_track = timeline.track(TrackType.VIDEO)
    if video_track is None or not video_track.items:
        raise ValueError("A render needs at least one video clip.")

    workspace = workspace.resolve()
    output_path = workspace / "output.mp4"

    argv: list[str] = [
        ffmpeg_path,
        # Fail rather than prompt. An interactive ffmpeg in a worker hangs
        # until the job times out.
        "-nostdin",
        "-y",
        "-hide_banner",
        "-loglevel",
        "error",
    ]

    inputs: list[Path] = []
    for item in sorted(video_track.items, key=lambda entry: entry.start_ms):
        if item.object_key is None:
            raise ValueError("A video timeline item must reference an object key.")
        path = local_paths.get(item.object_key)
        if path is None:
            raise ValueError(f"No downloaded file for {item.object_key!r}.")
        argv.extend(["-i", str(path)])
        inputs.append(path)

    voice_track = timeline.track(TrackType.VOICE)
    voice_index: int | None = None
    if voice_track and voice_track.items:
        first = voice_track.items[0]
        if first.object_key and (path := local_paths.get(first.object_key)):
            argv.extend(["-i", str(path)])
            voice_index = len(inputs)
            inputs.append(path)

    bgm_track = timeline.track(TrackType.BGM)
    bgm_index: int | None = None
    bgm_gain = 0.18
    if bgm_track and bgm_track.items:
        first = bgm_track.items[0]
        if first.object_key and (path := local_paths.get(first.object_key)):
            argv.extend(["-i", str(path)])
            bgm_index = len(inputs)
            bgm_gain = first.gain
            inputs.append(path)

    filters: list[str] = []
    clip_count = len(video_track.items)

    # Scale and pad every clip to the canvas before concatenating. Clips from
    # different providers arrive at different sizes, and `concat` refuses a
    # mismatch — padding rather than cropping, because cropping a product out
    # of its own advert is worse than a letterbox.
    width, height = timeline.canvas.width, timeline.canvas.height
    for index in range(clip_count):
        filters.append(
            f"[{index}:v]scale={width}:{height}:force_original_aspect_ratio=decrease,"
            f"pad={width}:{height}:(ow-iw)/2:(oh-ih)/2:color=black,"
            f"setsar=1,fps={timeline.canvas.fps}[v{index}]"
        )

    concat_inputs = "".join(f"[v{index}]" for index in range(clip_count))
    filters.append(f"{concat_inputs}concat=n={clip_count}:v=1:a=0[vcat]")

    video_label = "vcat"
    sidecars: dict[Path, str] = {}

    subtitle_track = timeline.track(TrackType.SUBTITLE)
    if burn_subtitles and subtitle_track and subtitle_track.items:
        from backend_core.render.subtitles import SubtitleCue, to_srt

        srt_path = workspace / "subtitles.srt"
        sidecars[srt_path] = to_srt(
            [
                SubtitleCue(start_ms=item.start_ms, end_ms=item.end_ms, text=item.text)
                for item in sorted(subtitle_track.items, key=lambda entry: entry.start_ms)
            ]
        )
        # The path is one we generated in our own temp directory, so it
        # contains no filter metacharacters (§35). A user-supplied name here
        # would need escaping and would still be a bad idea.
        filters.append(
            f"[{video_label}]subtitles={_escape_filter_path(srt_path)}:"
            f"force_style='{_SUBTITLE_STYLE}'[vout]"
        )
        video_label = "vout"

    audio_label = _build_audio_filters(filters, voice_index, bgm_index, bgm_gain)

    argv.extend(["-filter_complex", ";".join(filters)])
    argv.extend(["-map", f"[{video_label}]"])
    if audio_label:
        argv.extend(["-map", f"[{audio_label}]"])
    else:
        # No audio at all. An MP4 with no audio track confuses some players and
        # every downstream muxer, so a silent track is generated instead.
        argv.extend(["-f", "lavfi", "-i", "anullsrc=channel_layout=stereo:sample_rate=44100"])
        argv.extend(["-map", f"{len(inputs)}:a"])
        argv.extend(["-shortest"])

    argv.extend(["-crf", crf])
    argv.extend(_BASE_OUTPUT_ARGS)
    argv.append(str(output_path))

    return RenderPlan(
        argv=argv,
        output_path=output_path,
        sidecar_files=sidecars,
        expected_duration_ms=timeline.duration_ms,
    )


def _build_audio_filters(
    filters: list[str], voice_index: int | None, bgm_index: int | None, bgm_gain: float
) -> str | None:
    """Mix narration over music, or pass one through, or neither.

    `amix` with `duration=first` rather than `longest`: the narration defines
    the video's audio length, and letting a five-minute music bed extend the
    output would produce a video of the wrong duration.
    """
    if voice_index is None and bgm_index is None:
        return None

    if voice_index is not None and bgm_index is not None:
        filters.append(f"[{bgm_index}:a]volume={bgm_gain:.2f}[bgmq]")
        filters.append(
            f"[{voice_index}:a][bgmq]amix=inputs=2:duration=first:dropout_transition=0[aout]"
        )
        return "aout"

    source = voice_index if voice_index is not None else bgm_index
    gain = 1.0 if voice_index is not None else bgm_gain
    filters.append(f"[{source}:a]volume={gain:.2f}[aout]")
    return "aout"


def _escape_filter_path(path: Path) -> str:
    """Escape a path for ffmpeg's filter grammar.

    Only ever applied to paths this system generated, so in practice there is
    nothing to escape — but the filter grammar treats `:` and `'` specially and
    a temp directory on a platform that allows them would silently produce a
    broken filter chain rather than an error.
    """
    text = str(path)
    for character in ("\\", ":", "'", "[", "]", ","):
        text = text.replace(character, f"\\{character}")
    return text


def build_thumbnail_plan(
    video_path: Path, *, output_path: Path, at_ms: int = 1000, ffmpeg_path: str = "ffmpeg"
) -> list[str]:
    """A single frame for the project's poster image (§34).

    A second in rather than frame zero: the first frame of a generated clip is
    often a fade-in from black, which makes a poster nobody would click.
    """
    return [
        ffmpeg_path,
        "-nostdin",
        "-y",
        "-hide_banner",
        "-loglevel",
        "error",
        "-ss",
        f"{at_ms / 1000:.3f}",
        "-i",
        str(video_path),
        "-frames:v",
        "1",
        "-q:v",
        "3",
        str(output_path),
    ]


__all__ = ["RenderPlan", "build_render_plan", "build_thumbnail_plan"]
